#公共配置
spring:
  profiles:
    active: local
  activiti:
    check-process-definitions: false
    historyLevel: full
    jobExecutorActivate: true
    database-schema-update: true
    async-executor-activate: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    default-property-inclusion: non_null
mybatis:
  type-aliases-package: com.miz.ying.model
  mapper-locations: classpath:mapper/*.xml
---
#local环境
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti_test?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: root
    password: ying
    driver-class-name: com.mysql.cj.jdbc.Driver
domain: http://localhost:8090
server:
  port: 8090
---
#dev环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti_test?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: root
    password: ying
    driver-class-name: com.mysql.cj.jdbc.Driver
domain: http://localhost:8888
server:
  port: 8888